FROM node:20-alpine
WORKDIR /app

# Copy package files and install
COPY package*.json ./
RUN npm install

# Copy rest of the code
COPY . .

# Build your React app
RUN npm run build

# Serve it using React's dev server
EXPOSE 3000
CMD ["npm", "start"]
