package securityservice

import (
	"math"
	"net/http"
	"strings"

	"github-pat-backend/pkg/database"
	"github-pat-backend/pkg/response"

	"github.com/gin-gonic/gin"
)

type ScoreRequest struct {
	SessionToken string `json:"session_token" binding:"required"`
}

type ScoreResponse struct {
	TotalFindings      int     `json:"total_findings"`
	Critical           int     `json:"critical"`
	High               int     `json:"high"`
	Low                int     `json:"low"`
	CriticalPercentage float64 `json:"critical_percentage"`
	HighPercentage     float64 `json:"high_percentage"`
	LowPercentage      float64 `json:"low_percentage"`
	SecurityScore      float64 `json:"security_score"`
	OverallGrade       string  `json:"overall_grade"`
	CriticalityLevel   string  `json:"criticality_level"`
	HasValidationData  bool    `json:"has_validation_data"`
}

type findingSeverityRow struct {
	Severity string
}

// GetScore calculates security score strictly from findings generated by validation checks.
func GetScore(c *gin.Context) {
	var req ScoreRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.BadRequest(c, "session_token is required", err)
		return
	}

	// Validate session
	githubUsername, err := database.ValidateSession(req.SessionToken)
	if err != nil {
		response.Unauthorized(c, "invalid or expired session", err)
		return
	}

	// Get user's org_id
	orgID, err := database.GetUserOrgID(githubUsername)
	if err != nil {
		response.InternalError(c, "failed to get user organization", err)
		return
	}

	findings, err := getFindingsByOrgID(orgID)
	if err != nil {
		response.InternalError(c, "failed to fetch findings", err)
		return
	}

	scoreResp := calculateSecurityScore(findings)

	response.Success(c, http.StatusOK, "security score calculated successfully", scoreResp)
}

func getFindingsByOrgID(orgID string) ([]findingSeverityRow, error) {
	rows, err := database.DB.Query(`
		SELECT COALESCE(LOWER(severity), 'low') AS severity
		FROM findings
		WHERE org_id = $1
	`, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	findings := make([]findingSeverityRow, 0)
	for rows.Next() {
		var row findingSeverityRow
		if err := rows.Scan(&row.Severity); err != nil {
			continue
		}
		findings = append(findings, row)
	}

	return findings, nil
}

func calculateSecurityScore(findings []findingSeverityRow) ScoreResponse {
	totalFindings := len(findings)
	if totalFindings == 0 {
		return ScoreResponse{
			TotalFindings:      0,
			Critical:           0,
			High:               0,
			Low:                0,
			CriticalPercentage: 0,
			HighPercentage:     0,
			LowPercentage:      0,
			SecurityScore:      0,
			OverallGrade:       "N/A",
			CriticalityLevel:   "High",
			HasValidationData:  false,
		}
	}

	criticalCount := 0
	highCount := 0
	lowCount := 0
	totalWeight := 0

	for _, finding := range findings {
		switch strings.ToLower(strings.TrimSpace(finding.Severity)) {
		case "critical":
			criticalCount++
			totalWeight += 5
		case "high":
			highCount++
			totalWeight += 3
		default:
			// "low", "medium" (legacy), or any other value → treated as low
			lowCount++
			totalWeight += 1
		}
	}

	maxWeight := totalFindings * 5
	securityScore := ((float64(maxWeight) - float64(totalWeight)) / float64(maxWeight)) * 100.0
	securityScore = roundToTwo(securityScore)

	criticalPct := roundToTwo((float64(criticalCount) / float64(totalFindings)) * 100.0)
	highPct := roundToTwo((float64(highCount) / float64(totalFindings)) * 100.0)
	lowPct := roundToTwo((float64(lowCount) / float64(totalFindings)) * 100.0)

	return ScoreResponse{
		TotalFindings:      totalFindings,
		Critical:           criticalCount,
		High:               highCount,
		Low:                lowCount,
		CriticalPercentage: criticalPct,
		HighPercentage:     highPct,
		LowPercentage:      lowPct,
		SecurityScore:      securityScore,
		OverallGrade:       getGrade(securityScore),
		CriticalityLevel:   getCriticalityLevel(securityScore),
		HasValidationData:  true,
	}
}

func getGrade(score float64) string {
	switch {
	case score >= 90:
		return "A"
	case score >= 80:
		return "B"
	case score >= 70:
		return "C"
	case score >= 60:
		return "D"
	default:
		return "F"
	}
}

func getCriticalityLevel(score float64) string {
	switch {
	case score >= 80:
		return "Low"
	case score >= 60:
		return "High"
	default:
		return "Critical"
	}
}

func roundToTwo(value float64) float64 {
	return math.Round(value*100) / 100
}
